# -*- coding: utf-8 -*-
"""nabirds_finetune_keras3_tf219.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14KY99OHeMHuSj48zCHqOeL1FxrW8_9Tz

# NABirds Fine-tuning — Keras 3 + TensorFlow 2.19 (GPU, Fast, Higher Accuracy)

This Colab notebook modernizes your previous setup to **Keras 3** on **TensorFlow 2.19**, keeps GPU fast paths, and uses a stronger fine-tuning recipe for **MobileNetV2**.

**Key features**
- Full dataset training (set `PERCENT_TO_USE = 1.0` by default)
- Keras 3 API with `KERAS_BACKEND=tensorflow`
- Mixed precision on GPU (A100) with a numerically-stable float32 output head
- Data pipeline optimized with caching, AUTOTUNE, prefetch, and non-deterministic scheduling
- Lightweight augmentation that helps fine-grained bird classes
- Two-phase training: warmup (frozen backbone) → fine-tune (AdamW + CosineDecay + label smoothing)
- EarlyStopping and best-weights checkpointing

## 0) Runtime setup & GPU sanity check

- Set **Runtime → Change runtime type → Hardware accelerator = GPU** (A100 if available).
- **Run the Install cell** next. After it finishes, **Runtime → Restart session**.
- Then return here and run the **Verify** cell.
"""

#@title 0.1 Install TensorFlow 2.19 and Keras 3 (then RESTART runtime)
# Clean potentially conflicting packages
!pip uninstall -y tensorflow tensorflow-cpu tf-nightly tf-nightly-cpu keras keras-nightly >/dev/null 2>&1
# Install GPU-enabled TF 2.19 & Keras 3
!pip install -U "tensorflow==2.19.*" "keras>=3.5.0,<4" >/dev/null

print("✅ Installed TensorFlow 2.19 and Keras 3. Please do: Runtime → Restart session, then run the next cell (0.2 Verify).")

#@title 0.2 Verify GPU & backend (run AFTER restart)
import os, subprocess, sys, platform
os.environ.setdefault("KERAS_BACKEND","tensorflow")  # Keras 3 uses TF backend

import tensorflow as tf
import keras

print("TF:", tf.__version__)
print("Keras:", keras.__version__)
print("Keras backend:", keras.backend.backend())

print("\nBuilt with CUDA:", tf.test.is_built_with_cuda())
print("Physical GPUs:", tf.config.list_physical_devices('GPU'))

try:
    smi = subprocess.run(["nvidia-smi"], capture_output=True, text=True, check=True).stdout
    print("\nNVIDIA-SMI head:")
    print(smi[:500])
except Exception as e:
    print("nvidia-smi check error:", e)

# Allow gradual growth (optional)
for g in tf.config.list_physical_devices('GPU'):
    try:
        tf.config.experimental.set_memory_growth(g, True)
    except Exception as e:
        print("set_memory_growth error:", e)

#@title 1.2 Deep Lake v3 setup (same source as previous notebook)
# Ensure Deep Lake v3 API (older semantics) like the prior notebook
try:
    import deeplake as dl
    _v = tuple(int(x) for x in dl.__version__.split(".")[:2])
    if _v >= (4, 0):
        raise ImportError("deeplake v4+ detected")
except Exception:
    !pip -q install "deeplake<4"
    import deeplake as dl

import os, time, random, numpy as np

RANDOM_SEED = 42
random.seed(RANDOM_SEED); np.random.seed(RANDOM_SEED)

# Same hub sources the previous notebook used
HUB_TRAIN = "hub://activeloop/nabirds-dataset-train"
HUB_VAL   = "hub://activeloop/nabirds-dataset-val"

# Same Drive combined dataset location
BASE_DRIVE = "/content/drive/MyDrive"
COMBINED_PATH_DRIVE = f"{BASE_DRIVE}/nabirds_combined_v3"

def _deeplake_ok(path: str) -> bool:
    try:
        ds = dl.load(path, read_only=True)
        ok = ("images" in ds.tensors) and ("labels" in ds.tensors) and (len(ds) > 0)
        ds.close()
        return ok
    except Exception:
        return False

def build_or_update_combined(percent_to_use: float, val_fraction: float):
    assert 0.10 <= float(percent_to_use) <= 1.00
    assert 0.0  < float(val_fraction)   < 1.0

    t0 = time.time()
    print("[Deep Lake] Loading hub datasets...")
    ds_train = dl.load(HUB_TRAIN, read_only=True)
    ds_val   = dl.load(HUB_VAL,   read_only=True)
    print(ds_train); print(ds_val)
    print("Hub load time (mins):", round((time.time()-t0)/60.0,3))

    if not _deeplake_ok(COMBINED_PATH_DRIVE):
        print(f"[Deep Lake] Creating combined dataset at {COMBINED_PATH_DRIVE}")
        ds_combined = dl.empty(COMBINED_PATH_DRIVE)
        for k in ds_train.tensors:
            if k not in ds_combined.tensors:
                ds_combined.create_tensor(k, htype=ds_train.tensors[k].htype, sample_compression=ds_train.tensors[k].sample_compression)
        print("[Deep Lake] Appending train samples...")
        ds_combined.append(ds_train[:])
        print("[Deep Lake] Appending val samples...")
        ds_combined.append(ds_val[:])
        ds_combined.commit("initial combine")
        ds_combined.close()
    else:
        print(f"[Deep Lake] Using existing combined dataset at {COMBINED_PATH_DRIVE}")

    ds_combined = dl.load(COMBINED_PATH_DRIVE, read_only=True)
    n_total = len(ds_combined)
    print(f"[Deep Lake] Combined samples: {n_total}")

    n_subset = int(round(n_total * float(percent_to_use)))
    idxs = np.arange(n_total, dtype=np.int64)
    rng  = np.random.default_rng(RANDOM_SEED)
    rng.shuffle(idxs)
    subset_idxs = idxs[:n_subset].tolist()

    n_val = int(round(len(subset_idxs) * float(val_fraction)))
    val_indices   = subset_idxs[:n_val]
    train_indices = subset_idxs[n_val:]
    print(f"[Deep Lake] subset={len(subset_idxs)} -> train={len(train_indices)}, val={len(val_indices)}")

    return ds_combined, train_indices, val_indices

def deeplake_indices_to_tfdata(ds, indices, img_size, num_classes=None, training=True):
    import tensorflow as tf
    def gen():
        for i in indices:
            s = ds[i]
            img = s["images"].numpy()
            lab = int(s["labels"].numpy())
            yield img, lab

    out_sig = (
        tf.TensorSpec(shape=(None, None, 3), dtype=tf.uint8),
        tf.TensorSpec(shape=(), dtype=tf.int32),
    )
    raw = tf.data.Dataset.from_generator(gen, output_signature=out_sig)

    def _prep(img, lbl):
        img = tf.image.convert_image_dtype(img, tf.float32)
        img = tf.image.resize(img, [img_size, img_size], antialias=True)
        img = (img * (1.0/127.5)) - 1.0  # MobileNetV2 scaling
        if num_classes is not None:
            lbl = tf.one_hot(lbl, num_classes, dtype=tf.float32)
        return img, lbl

    ds_tf = raw.map(_prep, num_parallel_calls=tf.data.AUTOTUNE)
    if training:
        ds_tf = ds_tf.cache()
        opts = tf.data.Options()
        opts.experimental_deterministic = False
        ds_tf = ds_tf.with_options(opts)
        ds_tf = ds_tf.shuffle(8192, reshuffle_each_iteration=True)

    ds_tf = ds_tf.batch(BATCH_SIZE, drop_remainder=training).prefetch(tf.data.AUTOTUNE)
    return ds_tf

"""## 1) Imports, knobs, and paths

By default this uses **Deep Lake** if available (same dataset you used previously). If you prefer a folder dataset (ImageNet-style `train/` and `val/` directories), set `USE_DEEPLAKE = False` and fill `DATA_DIR`.

"""

#@title 1.1 Imports & global knobs — Drive + legacy experiments folder
import os, math, json, time, pathlib, itertools
os.environ.setdefault("KERAS_BACKEND","tensorflow")

from typing import Optional, Tuple

import tensorflow as tf
import keras
from keras import layers, models, ops
from keras import mixed_precision
from keras.optimizers import Adam, AdamW
from keras.optimizers.schedules import CosineDecay
from keras.metrics import TopKCategoricalAccuracy

print("TF:", tf.__version__, "| Keras:", keras.__version__, "| Backend:", keras.backend.backend())

# ---- Mount Google Drive ----
try:
    from google.colab import drive  # type: ignore
    if not os.path.ismount("/content/drive"):
        drive.mount("/content/drive")
        print("[Drive] Mounted at /content/drive")
except Exception as e:
    print("Colab Drive not available or already mounted:", e)

# Mixed precision — enable only if a GPU is present
if tf.config.list_physical_devices('GPU'):
    mixed_precision.set_global_policy("mixed_float16")
    print("Mixed precision policy:", mixed_precision.global_policy())
else:
    print("No GPU visible — mixed precision not enabled.")

# ------------------- knobs -------------------
IMG_SIZE        = 224
BATCH_SIZE      = 256      # A100 can often do 256–384 for MobileNetV2
PERCENT_TO_USE  = 1.0      # use 100% of data
VAL_SPLIT       = 0.1      # only used for auto-split/Deep Lake subset
NUM_CLASSES     = None     # will be inferred

EPOCHS_WARMUP   = 2
EPOCHS_FINETUNE = 10

LR_WARMUP       = 1e-3
LR_FINE         = 3e-4
WEIGHT_DECAY    = 2e-5
FREEZE_RATIO    = 0.75     # unfreeze top 25%

# Data source flags
USE_DEEPLAKE    = True     # mirror previous notebook: Deep Lake by default
DEEPLAKE_PATH   = ""       # not used; we bootstrap a local combined dataset on Drive
DATA_DIR        = ""       # optional folder dataset path if you decide to use directories later

# ------------------- outputs on Drive -------------------
# Match the previous notebook's experiments folder
BASE_OUT = "/content/drive/MyDrive/nabirds_experiments"
os.makedirs(BASE_OUT, exist_ok=True)
print("Experiments dir:", BASE_OUT)

"""## 2) Data pipeline

We provide two loaders:

- **Deep Lake**: Keeps your existing source with a Python generator bridge plus aggressive prefetch to avoid starving the GPU.
- **Directory**: Uses `image_dataset_from_directory` for `train/` and `val/` folders.

Both paths map into a unified `tf.data` pipeline with augmentation, caching, AUTOTUNE, and non-deterministic scheduling.

"""

#@title 2.1 Augmentation & preprocessing
def make_augmenter():
    # MobileNetV2-friendly, lightweight
    return keras.Sequential([
        layers.RandomFlip("horizontal"),
        layers.RandomRotation(0.05),
        layers.RandomZoom(0.10),
        layers.RandomContrast(0.10),
    ], name="aug")

def preprocess_inputs(x):
    # MobileNetV2 expects [-1, 1]
    return (x * (1.0/127.5)) - 1.0

#@title 2.2 Deep Lake loader (optional)
def load_deeplake_ds(path: Optional[str] = None):
    try:
        import deeplake as dl
    except Exception as e:
        raise RuntimeError("deeplake is not installed. Set USE_DEEPLAKE=False or install deeplake") from e

    if not path:
        # Try to discover from Drive mount or env
        # You can edit this default to your dataset location
        path = os.environ.get("DEEPLAKE_DATASET", "")
        if not path:
            raise RuntimeError("Please set DEEPLAKE_PATH or DEEPLAKE_DATASET environment variable.")

    ds = dl.load(path, read_only=True)
    if "images" not in ds.tensors or "labels" not in ds.tensors:
        raise RuntimeError("Deep Lake dataset must have 'images' and 'labels' tensors.")

    # Infer classes and mapping
    classes = sorted(list(set(int(x) for x in ds.labels.numpy(aslist=True))))
    num_classes = len(classes)

    # Python generator to bridge → tf.data, with buffer prefetch to avoid GPU starvation
    def gen():
        for sample in ds:
            # Expect HWC uint8 image and int label
            img = sample.images.numpy()
            lbl = int(sample.labels.numpy())
            yield img, lbl

    output_sig = (
        tf.TensorSpec(shape=(None, None, 3), dtype=tf.uint8),
        tf.TensorSpec(shape=(), dtype=tf.int32),
    )

    tfds = tf.data.Dataset.from_generator(gen, output_signature=output_sig)

    return tfds, num_classes

def prep_pipeline_from_raw(ds_raw: tf.data.Dataset, num_classes: int, training: bool):
    # Select percent
    if PERCENT_TO_USE < 1.0:
        take_n = int(1_000_000_000 * PERCENT_TO_USE)  # overshoot; we'll rely on cardinality if known
        ds_raw = ds_raw.take(take_n)

    def _prep(img, lbl):
        img = tf.image.convert_image_dtype(img, tf.float32)  # [0,1]
        img = tf.image.resize(img, [IMG_SIZE, IMG_SIZE], antialias=True)
        img = preprocess_inputs(img)
        lbl = tf.one_hot(lbl, num_classes, dtype=tf.float32)
        return img, lbl

    ds = ds_raw.map(_prep, num_parallel_calls=tf.data.AUTOTUNE)

    if training:
        # Optional cache (memory permitting)
        ds = ds.cache()
        # Non-deterministic for speed
        opts = tf.data.Options()
        opts.experimental_deterministic = False
        ds = ds.with_options(opts)
        # Shuffle, batch, prefetch
        ds = ds.shuffle(8192, reshuffle_each_iteration=True)

    ds = ds.batch(BATCH_SIZE, drop_remainder=training)
    ds = ds.prefetch(tf.data.AUTOTUNE)
    return ds

#@title 2.3 Directory loader (supports train/val or single root with classes)
def load_dir_ds(data_dir: str, allow_auto_split: bool = True, val_split: float = None):
    """
    Supports:
      A) data_dir/train/<class>/*.jpg and data_dir/val/<class>/*.jpg
      B) data_dir/<class>/*.jpg    (auto split when allow_auto_split=True)
    """
    if val_split is None:
        # fall back to global VAL_SPLIT if not given
        try:
            vs = float(VAL_SPLIT)
        except:
            vs = 0.1
        val_split = vs

    train_dir = os.path.join(data_dir, "train")
    val_dir   = os.path.join(data_dir, "val")

    def _prep_builder(num_classes: int):
        def _prep(img, lbl):
            img = tf.image.convert_image_dtype(img, tf.float32)  # [0,1]
            img = preprocess_inputs(img)
            lbl = tf.one_hot(lbl, num_classes, dtype=tf.float32)
            return img, lbl
        return _prep

    def _finalize(ds, training, num_classes):
        ds = ds.map(_prep_builder(num_classes), num_parallel_calls=tf.data.AUTOTUNE)
        if PERCENT_TO_USE < 1.0:
            ds = ds.take(int(1e9 * PERCENT_TO_USE))  # simple cap
        if training:
            ds = ds.cache()
            opts = tf.data.Options()
            opts.experimental_deterministic = False
            ds = ds.with_options(opts)
            ds = ds.shuffle(8192, reshuffle_each_iteration=True)
        ds = ds.batch(BATCH_SIZE, drop_remainder=training)
        ds = ds.prefetch(tf.data.AUTOTUNE)
        return ds

    if os.path.isdir(train_dir) and os.path.isdir(val_dir):
        # Layout A
        print(f"[dir] Using train/val under: {data_dir}")
        train_raw = tf.keras.utils.image_dataset_from_directory(
            train_dir, image_size=(IMG_SIZE, IMG_SIZE),
            batch_size=None, label_mode="int", shuffle=True, seed=42
        )
        val_raw = tf.keras.utils.image_dataset_from_directory(
            val_dir, image_size=(IMG_SIZE, IMG_SIZE),
            batch_size=None, label_mode="int", shuffle=False
        )
        class_names = train_raw.class_names
        num_classes = len(class_names)
        return _finalize(train_raw, True, num_classes), _finalize(val_raw, False, num_classes), num_classes

    # Layout B (single root) — auto split
    if allow_auto_split:
        print(f"[dir] Using single-root dataset with auto split at: {data_dir} (val_split={val_split})")
        train_raw = tf.keras.utils.image_dataset_from_directory(
            data_dir, image_size=(IMG_SIZE, IMG_SIZE),
            batch_size=None, label_mode="int",
            validation_split=val_split, subset="training",
            shuffle=True, seed=42
        )
        val_raw = tf.keras.utils.image_dataset_from_directory(
            data_dir, image_size=(IMG_SIZE, IMG_SIZE),
            batch_size=None, label_mode="int",
            validation_split=val_split, subset="validation",
            shuffle=False, seed=42
        )
        class_names = train_raw.class_names
        num_classes = len(class_names)
        return _finalize(train_raw, True, num_classes), _finalize(val_raw, False, num_classes), num_classes

    # If we get here, the layout was not recognized
    listing = []
    try:
        listing = os.listdir(data_dir)[:20]
    except Exception:
        pass
    raise RuntimeError(
        "DATA_DIR must either:\n"
        "  A) contain 'train' and 'val' subfolders, each with class subfolders, or\n"
        "  B) be a single folder with class subfolders (we will auto-split).\n"
        f"DATA_DIR: {data_dir}\n"
        f"Found entries (first 20): {listing}"
    )

"""## 3) Build MobileNetV2 model (Keras 3)

We insert augmentation into the model so it runs on GPU, keep the backbone frozen for warmup, and add a float32 output head for numerical stability under mixed precision.

"""

#@title 3.1 Model builder
def build_model(num_classes: int):
    inputs = layers.Input(shape=(IMG_SIZE, IMG_SIZE, 3), dtype="float32")
    x = make_augmenter()(inputs)  # training-only aug
    x = layers.Lambda(preprocess_inputs, name="preprocess")(x)

    base = keras.applications.MobileNetV2(
        include_top=False,
        input_shape=(IMG_SIZE, IMG_SIZE, 3),
        weights="imagenet"
    )
    base.trainable = False

    feats = base(x, training=False)
    feats = layers.GlobalAveragePooling2D(name="gap")(feats)
    feats = layers.Dropout(0.2, name="drop")(feats)

    # Keep final dense in float32; export probs as float32 for metrics/loss stability
    logits = layers.Dense(num_classes, dtype="float32", name="logits")(feats)
    probs  = layers.Activation("softmax", dtype="float32", name="probs")(logits)

    model = keras.Model(inputs, probs, name="mobilenetv2_nabirds_k3")
    model._backbone = base
    return model

def unfreeze_top(model: keras.Model, ratio: float = 0.75, freeze_bn: bool = True):
    base = getattr(model, "_backbone", None)
    if base is None:
        return
    n = len(base.layers)
    cut = int(n * ratio)
    for i, layer in enumerate(base.layers):
        trainable = (i >= cut)
        layer.trainable = trainable
        if freeze_bn and isinstance(layer, (layers.BatchNormalization,)):
            layer.trainable = False

"""## 4) Training

Two phases:
1. **Warmup**: backbone frozen, Adam, higher LR, label smoothing, Top-5 metric.
2. **Fine-tune**: unfreeze top 25 percent of backbone, **AdamW + CosineDecay**, gradient clipping, EarlyStopping, best checkpoint.

"""

#@title 4.1 Prepare data (Deep Lake train/val → tf.data; cached on Drive; no combine, self-contained)

# This cell is self-contained: it mounts Drive, ensures deeplake<4, caches
# hub://activeloop/nabirds-dataset-{train,val} into Drive (if available),
# and builds train_ds / val_ds using only images + labels.

import os, numpy as np, tensorflow as tf

# --- knobs (fallbacks if not defined earlier) ---
PERCENT_TO_USE = float(globals().get("PERCENT_TO_USE", 1.0))   # 0.1..1.0
IMG_SIZE       = int(globals().get("IMG_SIZE", 224))
BATCH_SIZE     = int(globals().get("BATCH_SIZE", 256))

# --- Mount Drive ---
try:
    from google.colab import drive  # type: ignore
    if not os.path.ismount("/content/drive"):
        drive.mount("/content/drive")
        print("[Drive] Mounted at /content/drive")
except Exception as e:
    print("Drive mount:", e)

# --- Deep Lake v3 (matches previous notebook API) ---
try:
    import deeplake as dl
    _v = tuple(int(x) for x in dl.__version__.split(".")[:2])
    if _v >= (4, 0):
        raise ImportError("deeplake v4+ detected")
except Exception:
    !pip -q install "deeplake<4"
    import deeplake as dl

# --- Sources and local cache paths ---
BASE_DRIVE   = "/content/drive/MyDrive"
DL_CACHE     = f"{BASE_DRIVE}/deeplake_splits"
os.makedirs(DL_CACHE, exist_ok=True)

HUB_TRAIN    = "hub://activeloop/nabirds-dataset-train"
HUB_VAL      = "hub://activeloop/nabirds-dataset-val"
LOCAL_TRAIN  = f"{DL_CACHE}/nabirds_train"
LOCAL_VAL    = f"{DL_CACHE}/nabirds_val"

# --- Non-blocking cache helpers (no sleeps) ---
def _try_open(path: str) -> bool:
    try:
        ds = dl.load(path, read_only=True)
        ok = ("images" in ds.tensors) and ("labels" in ds.tensors)
        ds.close()
        return bool(ok)
    except Exception:
        return False

def _ensure_local(hub_src: str, local_dst: str):
    """Prefer a local cached split if it opens; else copy once and use hub this run."""
    if _try_open(local_dst):
        print(f"[Deep Lake] Using cached split at {local_dst}")
        return local_dst
    print(f"[Deep Lake] Caching split from {hub_src} → {local_dst}")
    dl.copy(hub_src, local_dst, overwrite=os.path.exists(local_dst))
    if _try_open(local_dst):
        print(f"[Deep Lake] Cached and ready: {local_dst}")
        return local_dst
    print(f"[Deep Lake] Cache copied but not ready yet — using HUB for this run: {hub_src}")
    return hub_src

# --- Resolve dataset paths (instant) ---
TRAIN_PATH = _ensure_local(HUB_TRAIN, LOCAL_TRAIN)
VAL_PATH   = _ensure_local(HUB_VAL,   LOCAL_VAL)

# --- Load datasets (hub or local, whichever is ready) ---
ds_train = dl.load(TRAIN_PATH, read_only=True)
ds_val   = dl.load(VAL_PATH,   read_only=True)
print(f"[Deep Lake] Train samples: {len(ds_train)}  |  Val samples: {len(ds_val)}")

# --- Build tf.data using ONLY images + labels (ignore other tensors like 'boxes') ---
def _indices_subset(n, percent):
    n_sub = int(round(n * float(percent)))
    idxs = np.arange(n, dtype=np.int64)
    rng  = np.random.default_rng(42)
    rng.shuffle(idxs)
    return idxs[:n_sub].tolist()

train_indices = _indices_subset(len(ds_train), PERCENT_TO_USE)
val_indices   = _indices_subset(len(ds_val),   PERCENT_TO_USE)

def deeplake_to_tfdata(ds, indices, img_size, num_classes=None, training=True):
    def gen():
        for i in indices:
            s = ds[i]
            img = s["images"].numpy()
            lab = int(s["labels"].numpy().item())  # scalarize 0-D array label
            yield img, lab

    out_sig = (
        tf.TensorSpec(shape=(None, None, 3), dtype=tf.uint8),
        tf.TensorSpec(shape=(), dtype=tf.int32),
    )
    raw = tf.data.Dataset.from_generator(gen, output_signature=out_sig)

    def _prep(img, lbl):
        img = tf.image.convert_image_dtype(img, tf.float32)
        img = tf.image.resize(img, [img_size, img_size], antialias=True)
        img = (img * (1.0/127.5)) - 1.0  # MobileNetV2 scaling to [-1, 1]
        if num_classes is not None:
            lbl = tf.one_hot(lbl, num_classes, dtype=tf.float32)
        return img, lbl

    ds_tf = raw.map(_prep, num_parallel_calls=tf.data.AUTOTUNE)
    if training:
        ds_tf = ds_tf.cache()
        opts = tf.data.Options()
        opts.experimental_deterministic = False
        ds_tf = ds_tf.with_options(opts)
        ds_tf = ds_tf.shuffle(8192, reshuffle_each_iteration=True)

    return ds_tf.batch(BATCH_SIZE, drop_remainder=training).prefetch(tf.data.AUTOTUNE)

# --- Infer number of classes from a small probe across both splits ---
probe = []
for i in train_indices[:1024]:
    probe.append(int(ds_train[i]["labels"].numpy().item()))
for i in val_indices[:1024]:
    probe.append(int(ds_val[i]["labels"].numpy().item()))
num_classes = int(max(probe)) + 1
print("Num classes (inferred):", num_classes)

# --- Final datasets used by training ---
train_ds = deeplake_to_tfdata(ds_train, train_indices, IMG_SIZE, num_classes=num_classes, training=True)
val_ds   = deeplake_to_tfdata(ds_val,   val_indices,   IMG_SIZE, num_classes=num_classes, training=False)

# (Optional) close hub handles (not strictly necessary in read_only=True)
try:
    ds_train.close(); ds_val.close()
except Exception:
    pass

print("Datasets ready.")

#@title 4.2 Build & warmup (explicit steps + repeat to avoid exhaustion)
import math

model = build_model(num_classes)

loss = keras.losses.CategoricalCrossentropy(label_smoothing=0.1)
metrics = ["accuracy", TopKCategoricalAccuracy(k=5, name="top5")]

model.compile(
    optimizer=Adam(LR_WARMUP),
    loss=loss,
    metrics=metrics
)

# Compute steps explicitly from the index lists created in 4.1
n_train = len(train_indices)
n_val   = len(val_indices)

# training dataloader uses drop_remainder=True → floor division
steps_per_epoch = max(1, n_train // BATCH_SIZE)
# validation keeps the remainder → ceil
val_steps = max(1, math.ceil(n_val / BATCH_SIZE))

print("Warmup steps_per_epoch:", steps_per_epoch, "val_steps:", val_steps)

# IMPORTANT: repeat() makes datasets endless; steps_* bound each epoch
history_warm = model.fit(
    train_ds.repeat(),
    validation_data=val_ds.repeat(),
    epochs=EPOCHS_WARMUP,
    steps_per_epoch=steps_per_epoch,
    validation_steps=val_steps,
    verbose=1
)

#@title 4.3 Fine-tune
unfreeze_top(model, ratio=FREEZE_RATIO, freeze_bn=True)

total_ft_steps = (steps_per_epoch or 1000) * EPOCHS_FINETUNE
lr_schedule = CosineDecay(initial_learning_rate=LR_FINE, decay_steps=total_ft_steps, alpha=0.1)

opt_ft = AdamW(learning_rate=lr_schedule, weight_decay=WEIGHT_DECAY, clipnorm=1.0)

model.compile(
    optimizer=opt_ft,
    loss=keras.losses.CategoricalCrossentropy(label_smoothing=0.1),
    metrics=["accuracy", TopKCategoricalAccuracy(k=5, name="top5")]
)

ckpt_path = os.path.join(BASE_OUT, "mobilenetv2_nabirds_k3_best.keras")
callbacks = [
    keras.callbacks.ModelCheckpoint(
        ckpt_path, monitor="val_accuracy", mode="max",
        save_best_only=True, save_weights_only=False, verbose=1
    ),
    keras.callbacks.ReduceLROnPlateau(
        monitor="val_loss", factor=0.5, patience=2, min_lr=1e-6, verbose=1
    ),
    keras.callbacks.EarlyStopping(
        monitor="val_accuracy", mode="max", patience=3, restore_best_weights=True, verbose=1
    )
]

history_ft = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS_FINETUNE,
    steps_per_epoch=steps_per_epoch,
    validation_steps=val_steps,
    callbacks=callbacks,
    verbose=1
)

"""## 5) Evaluate & export"""

#@title 5.1 Final eval and save
eval_out = model.evaluate(val_ds, verbose=1)
print("Final eval:", dict(zip(model.metrics_names, eval_out)))

final_path = os.path.join(BASE_OUT, "mobilenetv2_nabirds_k3_final.keras")
model.save(final_path)
print("Saved:", final_path)

"""## Notes & tips

- If GPU stays idle even though `nvidia-smi` looks fine, the input pipeline is starving the GPU. Consider increasing `BATCH_SIZE` (A100 can often do **320–384** with 224×224 MobileNetV2), and make sure caching/prefetch are enabled.
- For Deep Lake: if your dataset already has `train` and `val` splits, replace the simple `take/skip` with the official split accessors for balanced splits.
- To push accuracy further, try **IMG_SIZE = 288** and lower the batch if you hit memory limits, or switch to EfficientNet-B0/B1 with the same training recipe.

"""