[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10, <3.11"
dependencies = [
    "google-cloud-aiplatform>=1.120.0",
    "google-cloud-storage",
    "requests",
    "python-json-logger==2.0.7",
    "tensorflowjs",
    "tensorflow==2.17.0",
    "keras==3.5.0",
    "numpy<2",
]
